"use strict";

const CREATED_STATUS = "created";
const DELETED_STATUS = "deleted";
const CHANGED_STATUS = "changed";
const UNCHANGED_STATUS = "unchanged";
const DEEP_VALUE_STATUS = "deep_value";
const ALL_STATUS_NAME = {
  CREATED_STATUS,
  DELETED_STATUS,
  CHANGED_STATUS,
  UNCHANGED_STATUS,
  DEEP_VALUE_STATUS,
};

module.exports = {
  CREATED_STATUS,
  DELETED_STATUS,
  CHANGED_STATUS,
  UNCHANGED_STATUS,
  DEEP_VALUE_STATUS,
  ALL_STATUS_NAME,
};
